export const offersProps = [
  {
    id: `1`,
    isCheckedPremium: true,
    images: [`test`],
    price: 120,
    ratingStars: 0.5,
    titleCard: `test`,
    typeCard: `test`,
    descriptions: [`test`],
    numberBadrooms: 1,
    numberGuests: 1,
    householdItems: [`test`],
    infoUser: {
      avatarUser: `test`,
      nameUser: `test`,
      markSuper: true,
    },
    coordinates: [52.3909553943508, 4.85309666406198],
  },

  {
    id: `2`,
    isCheckedPremium: false,
    images: [`test`],
    price: 80,
    ratingStars: 1.6,
    titleCard: `test`,
    typeCard: `test`,
    descriptions: [`test`],
    numberBadrooms: 1,
    numberGuests: 1,
    householdItems: [`test`],
    infoUser: {
      avatarUser: `test`,
      nameUser: `test`,
      markSuper: true,
    },
    coordinates: [52.369553943508, 4.85309666406198],
  },

  {
    id: `3`,
    isCheckedPremium: false,
    images: [`test`],
    price: 132,
    ratingStars: 2.5,
    titleCard: `test`,
    typeCard: `test`,
    descriptions: [`test`],
    numberBadrooms: 1,
    numberGuests: 1,
    householdItems: [`test`],
    infoUser: {
      avatarUser: `test`,
      nameUser: `test`,
      markSuper: true,
    },
    coordinates: [52.3909553943508, 4.929309666406198],
  },

  {
    id: `4`,
    isCheckedPremium: true,
    images: [`test`],
    price: 180,
    ratingStars: 4.5,
    titleCard: `test`,
    typeCard: `Apartment`,
    descriptions: [`test`],
    numberBadrooms: 1,
    numberGuests: 1,
    householdItems: [`test`],
    infoUser: {
      avatarUser: `test`,
      nameUser: `test`,
      markSuper: true,
    },
    coordinates: [52.3809553943508, 4.939309666406198],
  },
];

export const offerProps = {
  id: `1`,
  isCheckedPremium: true,
  images: [`test`],
  price: 120,
  ratingStars: 2.5,
  titleCard: `test`,
  typeCard: `test`,
  descriptions: [`test`],
  numberBadrooms: 1,
  numberGuests: 1,
  householdItems: [`test`],
  infoUser: {
    avatarUser: `test`,
    nameUser: `test`,
    markSuper: true,
  },
  coordinates: [52.3909553943508, 4.85309666406198],
};
